name: PESync to Dropbox

on:
  schedule:
    - cron: "0 0,12 * * *" # Run twice a day at 00:00 and 12:00 UTC
  workflow_dispatch: # Allow manual trigger from the GitHub UI

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        env:
          STORAGE_PROVIDER: ${{ secrets['STORAGE_PROVIDER'] }}
          DROPBOX_APP_KEY: ${{ secrets['DROPBOX_APP_KEY'] }}
          DROPBOX_APP_SECRET: ${{ secrets['DROPBOX_APP_SECRET'] }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets['DROPBOX_REFRESH_TOKEN'] }}
          GOOGLE_DRIVE_CLIENT_ID: ${{ secrets['GOOGLE_DRIVE_CLIENT_ID'] }}
          GOOGLE_DRIVE_CLIENT_SECRET: ${{ secrets['GOOGLE_DRIVE_CLIENT_SECRET'] }}
          GOOGLE_DRIVE_REFRESH_TOKEN: ${{ secrets['GOOGLE_DRIVE_REFRESH_TOKEN'] }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets['GOOGLE_DRIVE_FOLDER_ID'] }}
        run: python main.py
